# Generated by Django 3.1.7 on 2021-10-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
