# Generated by Django 3.1.7 on 2021-10-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20211029_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
